on: push

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-22.04
          - macos-13
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Elixir
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.3"
          elixir-version: "1.17.3"
      - name: Set up Elixir
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: brew install elixir
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get dependencies
        run: mix deps.get --only dev
      - name: Restore PLTs
        uses: actions/cache@v4
        with:
          path: _build/dev/plt
          key: plt-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            plt-${{ github.ref }}-${{ github.sha }}
            plt-${{ github.ref }}-
            plt-refs/heads/master-
      - name: Install system deps
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt install   \
            build-essential  \
            devscripts       \
            equivs           \
            libtasn1-6-dev   \
            libjson-glib-dev \
            libseccomp-dev   \
            libgmp-dev
      - name: Install system deps
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: brew install automake gawk socat json-glib
      - name: Compile
        run: mix compile
  type_check:
    name: Type Check
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.3"
          elixir-version: "1.17.3"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get dependencies
        run: mix deps.get --only dev
      - name: Restore PLTs
        uses: actions/cache@v4
        with:
          path: _build/dev/plt
          key: plt-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            plt-${{ github.ref }}-${{ github.sha }}
            plt-${{ github.ref }}-
            plt-refs/heads/master-
      - name: Install system deps
        run: |
          sudo apt install   \
            build-essential  \
            devscripts       \
            equivs           \
            libtasn1-6-dev   \
            libjson-glib-dev \
            libseccomp-dev   \
            libgmp-dev
      - name: Compile
        run: mix compile
      - name: Run dialyzer
        run: mix dialyzer
